import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import theme from "./theme";
import { ThemeProvider } from "@mui/material/styles";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </ThemeProvider>
  );
}
