export enum Status {
  draft = "draft",
  pending = "pending",
  approved = "approved",
  rejected = "rejected",
  deleted = "deleted",
  closed = "closed",
  published = "published",
  reopened = "reopened",
  approval_requested = "approval_requested",
  edit_requested = "edit_requested",
  publish_requested = "publish_requested",
  approval_rejected = "approval_rejected",
  edit_rejected = "edit_rejected",
  publish_rejected = "publish_rejected",
  edit_approved = "edit_approved",
  publish_approved = "publish_approved",
  reopen_requested = "reopen_requested",
  reopen_rejected = "reopen_rejected",
  reopen_publish_requested = "reopen_publish_requested",
  reopen_publish_rejected = "reopen_publish_rejected",
}
